app = 'shutters-dataplane'
primary_region = 'lhr'

[build]
  dockerfile = "../../Dockerfile"

[build.args]
  service = "dataplane"

[processes]
  app = '/usr/local/bin/start'

[metrics]
  port = 3000
  path = "/metrics"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 3000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    handlers = ["http"]
    port = 80
