---
volumes:
  dbdata: {}

services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - dbdata:/var/lib/sqld
