app = 'shutters-cdn'
primary_region = 'lhr'

[build]
  dockerfile = "../../Dockerfile"

[build.args]
  service = "cdn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = '/usr/local/bin/start'

[metrics]
  port = 3000
  path = "/metrics"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true
