/* eslint-disable */
// This file is automatically generated, do not edit!

/**
 * @module
 * Shutters.social Lexicons
 */

import "@atcute/client/lexicons";

declare module "@atcute/client/lexicons" {
  namespace SocialShuttersActorDefs {}

  namespace SocialShuttersActorProfile {
    /** A declaration of a Shutters profile. */
    interface Record {
      $type: "social.shutters.actor.profile";
      /** Small image to be displayed next to posts from account. AKA, 'profile picture' */
      avatar?: At.Blob;
      createdAt?: string;
      /**
       * Free-form profile description text. \
       * Maximum string length: 2560 \
       * Maximum grapheme length: 256
       */
      description?: string;
      /**
       * Maximum string length: 640 \
       * Maximum grapheme length: 64
       */
      displayName?: string;
    }
  }

  interface Records {
    "social.shutters.actor.profile": SocialShuttersActorProfile.Record;
  }

  interface Queries {}

  interface Procedures {}
}
