# Deploys a service to the specified environment.
---
name: Deploy service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy service ${{ inputs.service-name }} to shutters-${{ inputs.env }}
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.service-name }}-${{ inputs.env }}-deploy
    steps:
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          FLY_API_TOKEN: op://shutters-cicd/shutters-${{ inputs.env }}/flytoken
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl secrets set \
            --stage \
            --config "services/${{ inputs.service-name }}/fly.toml" \
            "SENTRY_ENV=${{ inputs.service-name }}"
      - run: |
          flyctl deploy . \
            --config "services/${{ inputs.service-name }}/fly.toml" \
            --remote-only \
            --build-arg "vcs_ref=$(git rev-parse --short HEAD)"
