# Deploys multiple services to the dev environment.
---
name: Dev Deploy
on:
  push:
    branches:
      - main

jobs:
  api:
    uses: ./deploy.yaml
    with:
      service-name: api
      env: dev

  cdn:
    uses: ./deploy.yaml
    with:
      service-name: cdn
      env: dev
