# Deploys multiple services to the dev environment.
---
name: Dev Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        service: [api, cdn, dataplane]
    uses: ./.github/workflows/deploy.yaml
    with:
      service-name: ${{ matrix.service }}
      env: dev
    secrets: inherit
