# Deploys multiple services to the dev environment.
---
name: Dev Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        SERVICE_NAME: [api, cdn, dataplane]
    uses: ./.github/workflows/deploy.yaml
    with:
      service-name: ${SERVICE_NAME}
      env: dev
    secrets: inherit
